language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 5.4
    - php: 7.0
    - php: hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi;
  - echo memory_limit = -1 >> $INI_FILE
  - echo session.gc_probability = 0 >> $INI_FILE
  - composer self-update
  - composer require -n --prefer-dist symfony/symfony:${SYMFONY_VERSION}

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - javer@argentum.ua
